In [1]:
import pandas as pd
import numpy as np

In [5]:
df=pd.read_csv("emft- Sheet1.csv")

In [7]:
df

      Charge   Distribution type
0   37.485855       point charge
1   22.199741        line charge
2   28.111029  Distribution type
3   49.970334       point charge
4   66.041516        line charge
5   72.500766  Distribution type
6    7.430764       point charge
7   30.292556        line charge
8   99.227356  Distribution type
9   64.467522       point charge
10   1.084460        line charge
11  26.328859  Distribution type
12  59.973514       point charge

In [13]:
df["Electric Field Intensity"]=np.zeros(13)

In [31]:
df2=df.replace("Distribution type","Spherical")
df2["Distance"]=np.random.randint(20)
df2

      Charge  Distribution type  Electric Field Intensity  Distance
0   37.485855      point charge                       0.0         5
1   22.199741       line charge                       0.0         5
2   28.111029         Spherical                       0.0         5
3   49.970334      point charge                       0.0         5
4   66.041516       line charge                       0.0         5
5   72.500766         Spherical                       0.0         5
6    7.430764      point charge                       0.0         5
7   30.292556       line charge                       0.0         5
8   99.227356         Spherical                       0.0         5
9   64.467522      point charge                       0.0         5
10   1.084460       line charge                       0.0         5
11  26.328859         Spherical                       0.0         5
12  59.973514      point charge                       0.0         5

In [44]:
for dis in df2["Distribution type"]:
    if dis == "point charge":
        df2["Electric Field Intensity"]=9*10**(9)*df2["Charge "]/(df2["Distance"])**2
    if dis == "line charge":
        df2["Electric Field Intensity"]=2*9*10**(9)*df2["Charge "]/df2["Distance"]
    if dis == "Spherical":
        df2["Electric Field Intensity"]=2*9*10**(9)*df2["Charge "]/df2["Distance"]

In [42]:
df2.columns

Index(['Charge ', 'Distribution type', 'Electric Field Intensity', 'Distance'], dtype='object')

In [46]:
df2

      Charge  Distribution type  Electric Field Intensity  Distance
0   37.485855      point charge              1.349491e+10         5
1   22.199741       line charge              7.991907e+09         5
2   28.111029         Spherical              1.011997e+10         5
3   49.970334      point charge              1.798932e+10         5
4   66.041516       line charge              2.377495e+10         5
5   72.500766         Spherical              2.610028e+10         5
6    7.430764      point charge              2.675075e+09         5
7   30.292556       line charge              1.090532e+10         5
8   99.227356         Spherical              3.572185e+10         5
9   64.467522      point charge              2.320831e+10         5
10   1.084460       line charge              3.904056e+08         5
11  26.328859         Spherical              9.478389e+09         5
12  59.973514      point charge              2.159046e+10         5

In [54]:
df2["Net Flux"]=df2["Charge "]/((8.854)*10**(-12)) 
df2

,Charge,Distribution type,Electric Field Intensity,Distance,Net Flux
0,37.485855,point charge,1.349491e+10,5,4.233776e+12
1,22.199741,line charge,7.991907e+09,5,2.507312e+12
2,28.111029,Spherical,1.011997e+10,5,3.174952e+12
3,49.970334,point charge,1.798932e+10,5,5.643815e+12
4,66.041516,line charge,2.377495e+10,5,7.458947e+12
5,72.500766,Spherical,2.610028e+10,5,8.188476e+12
6,7.430764,point charge,2.675075e+09,5,8.392551e+11
7,30.292556,line charge,1.090532e+10,5,3.421341e+12
8,99.227356,Spherical,3.572185e+10,5,1.120707e+13
9,64.467522,point charge,2.320831e+10,5,7.281175e+12
10,1.084460,line charge,3.904056e+08,5,1.224825e+11
11,26.328859,Spherical,9.478389e+09,5,2.973668e+12
12,59.973514,point charge,2.159046e+10,5,6.773607e+12

In [56]:
df2

,Charge,Distribution type,Electric Field Intensity,Distance,Net Flux
0,37.485855,point charge,1.349491e+10,5,4.233776e+12
1,22.199741,line charge,7.991907e+09,5,2.507312e+12
2,28.111029,Spherical,1.011997e+10,5,3.174952e+12
3,49.970334,point charge,1.798932e+10,5,5.643815e+12
4,66.041516,line charge,2.377495e+10,5,7.458947e+12
5,72.500766,Spherical,2.610028e+10,5,8.188476e+12
6,7.430764,point charge,2.675075e+09,5,8.392551e+11
7,30.292556,line charge,1.090532e+10,5,3.421341e+12
8,99.227356,Spherical,3.572185e+10,5,1.120707e+13
9,64.467522,point charge,2.320831e+10,5,7.281175e+12
10,1.084460,line charge,3.904056e+08,5,1.224825e+11
11,26.328859,Spherical,9.478389e+09,5,2.973668e+12
12,59.973514,point charge,2.159046e+10,5,6.773607e+12

In [58]:
df2.to_csv("emft.csv")